server:
  port: 80

spring:
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.150.3:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 442520

      redis:
        host: 192.160.158:6379
        database: 0
        password: 442520
        timeout: 1800000
        lettuce:
        pool:
        max-active: 20
        max-idle: 5
        min-idle: 0


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID



tencent:
      msm:
      id: AKIDVosyoNfhRu50e17xXqsc6JFuJRHq89tM
      secret: EBrGOFp8AvQeaFdkb7NM4UdW9UYLr64l
      endPoint: sms.tencentcloudapi.com
      appId: 1400714471
#      signName: 外卖编程公众号
      templateId: 1491829


reggie:
    path: D:\img\